"""Configuration file for the Sphinx documentation builder.

This file only contains a selection of the most common options. For a full list see the
documentation: https://www.sphinx-doc.org/en/master/usage/configuration.html

"""

import importlib.metadata

# -- Path setup ------------------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory, add
# these directories to sys.path here. If the directory is relative to the documentation
# root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))

# -- Project information ---------------------------------------------------------------

project = "Tripadvisor Hotel Reviews Topic Modeling"
copyright = "2022, RVU"
author = "RVU Data Science"

# The full version, including alpha/beta/rc tags
release = importlib.metadata.version("tripadvisor_hotel_reviews_topic_modeling")


# -- General configuration -------------------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be extensions coming
# with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosectionlabel",
    "sphinx.ext.autosummary",
    "sphinx.ext.mathjax",
    "sphinx.ext.napoleon",
    "myst_parser",
    "sphinx_copybutton",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# List of patterns, relative to source directory, that match files and directories to
# ignore when looking for source files. This pattern also affects html_static_path and
# html_extra_path.
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]


# -- Options for HTML output -----------------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for a list of
# builtin themes.
html_theme = "pydata_sphinx_theme"

# Add any paths that contain custom static files (such as style sheets) here, relative
# to this directory. They are copied after the builtin static files, so a file named
# "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# Add custom CSS to the theme
html_css_files = ["custom.css"]

# RVU logo to appear in the top-left hand corner of the PyData Sphinx theme
html_logo = "_static/rvu-logo.svg"

# Set the theme options
html_theme_options = {
    "collapse_navigation": True,
    "navigation_depth": 2,
    "favicons": [
        {"rel": "apple-touch-icon", "sizes": "180x180", "href": "apple-touch-icon.png"},
        {
            "rel": "icon",
            "sizes": "32x32",
            "href": "favicon-32x32.png",
        },
        {
            "rel": "icon",
            "sizes": "16x16",
            "href": "favicon-16x16.png",
        },
        {
            "rel": "mask-icon",
            "sizes": "32x32",
            "color": "#e81919",
            "href": "safari-pinned-tab-32x32.svg",
        },
        {
            "rel": "shortcut icon",
            "sizes": "32x32",
            "href": "favicon-32x32.ico",
        },
    ],
    "icon_links": [
        {
            "name": "GitHub",
            "url": "https://github.com/uswitch/tripadvisor-hotel-reviews-topic-modeling",
            "icon": "fab fa-github-square",
        },
        {
            "name": "Twitter",
            "url": "https://twitter.com/rvueng",
            "icon": "fab fa-twitter-square",
        },
        {
            "name": "LinkedIn",
            "url": "https://www.linkedin.com/company/rvu-uk/",
            "icon": "fab fa-linkedin",
        },
        {
            "name": "Instagram",
            "url": "https://www.instagram.com/rvu.co.uk/",
            "icon": "fab fa-instagram-square",
        },
    ],
    "use_edit_page_button": True,
}

# Add context required for the "Edit this page" link
html_context = {
    "github_user": "uswitch",
    "github_repo": "tripadvisor-hotel-reviews-topic-modeling",
    "github_version": "main",
    "doc_path": "docs",
}
# -- Extension configuration -----------------------------------------------------------

# Prefix document path to section labels, otherwise autogenerated labels would look
# like 'heading' rather than 'path/to/file:heading'
autosectionlabel_prefix_document = True

# Set the autosummary to generate stub files
autosummary_generate = True

# Ignore certain firewalled links during linkcheck
linkcheck_ignore = [
    r"^https://.+\.authed\.rvu\.cloud",
    r"^https://console\.cloud\.google\.com/",
    r"^https://github\.com/uswitch/",
    r"^https://prod-uk-a\.online\.tableau\.com/",
    r"^https://www\.notion\.so/rvu/",
]

# Enforce MyST heading anchors for h1 to h6 headings
myst_heading_anchors = 6

# Enable MyST extensions
myst_enable_extensions = [
    "amsmath",
    "colon_fence",
    "deflist",
    "dollarmath",
    "html_admonition",
    "html_image",
    # "linkify",
    "replacements",
    "smartquotes",
    "substitution",
]
